# Generated by Django 5.2.8 on 2025-11-18 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("supplier", "Supplier"),
                            ("buyer", "Buyer"),
                            ("exporter", "Exporter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "identity_type",
                    models.CharField(
                        choices=[
                            ("ID_CARD", "ID Card (KTP)"),
                            ("PASSPORT", "Passport"),
                        ],
                        max_length=20,
                    ),
                ),
                ("identity_number", models.CharField(blank=True, max_length=50)),
                ("npwp", models.CharField(blank=True, max_length=50)),
                ("full_address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("mother_name", models.CharField(blank=True, max_length=100)),
                ("domicile", models.CharField(blank=True, max_length=100)),
                ("birth_place", models.CharField(blank=True, max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
