# Generated by Django 5.1.6 on 2025-11-17 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=128)),
                ('product_type', models.CharField(max_length=64)),
                ('volume_required', models.PositiveIntegerField()),
                ('allowed_contaminants', models.JSONField(default=dict)),
                ('shipping_window_start', models.DateField()),
                ('shipping_window_end', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('DONE', 'Settled')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('WARN', 'Warn'), ('FAIL', 'Fail')], default='PASS', max_length=16)),
                ('result', models.JSONField(default=dict)),
                ('hash', models.CharField(blank=True, max_length=64)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='buyers.buyerrequirement')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
