# Generated by Django 5.1.6 on 2025-11-18 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerrequirement',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyerrequirement',
            name='destination_country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='buyerrequirement',
            name='max_volume',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyerrequirement',
            name='min_volume',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyerrequirement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyerrequirement',
            name='standards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='buyerrequirement',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='buyerrequirement',
            name='volume_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BatchMarketInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=128)),
                ('size_min_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('size_max_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('country_of_origin', models.CharField(blank=True, max_length=64)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('ready_date', models.DateField(blank=True, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=64)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contaminant_mercury_ppm', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('contaminant_cesium_ppm', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('contaminant_ecoli_cfu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_info', to='suppliers.productbatch')),
            ],
            options={
                'ordering': ['-harvest_date', '-batch__created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
