# Generated by Django 5.2.8 on 2025-11-16 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_code", models.CharField(max_length=64, unique=True)),
                ("product_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.PositiveIntegerField()),
                ("unit", models.CharField(default="kg", max_length=32)),
                (
                    "qc_status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("submitted", "Submitted to BRIN"),
                            ("brin_verifying", "BRIN Verifying"),
                            ("brin_verified_pass", "BRIN Verified PASS"),
                            ("brin_verified_fail", "BRIN Verified FAIL"),
                        ],
                        default="not_submitted",
                        max_length=32,
                    ),
                ),
                ("brin_request_payload", models.JSONField(blank=True, null=True)),
                ("brin_response_payload", models.JSONField(blank=True, null=True)),
                ("is_allowed_for_catalog", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_qc_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QcRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("passed", models.BooleanField()),
                ("contamination_score", models.FloatField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("previous_hash", models.CharField(blank=True, max_length=128)),
                ("record_hash", models.CharField(blank=True, max_length=128)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_records",
                        to="suppliers.productbatch",
                    ),
                ),
            ],
        ),
    ]
